/**
 * Markdown documentation exporter
 */

import type { Flow } from "../agent/FlowTracker.js";

export function exportToMarkdown(flows: Flow[]): string {
  const sections: string[] = [];

  sections.push("# API Documentation\n");
  sections.push("Generated by WebDoc Agent\n");
  sections.push("---\n");

  for (const flow of flows) {
    sections.push(`## ${flow.name}\n`);

    for (const step of flow.steps) {
      sections.push(`### ${step.step}\n`);

      if (step.uiActions.length > 0) {
        sections.push("**UI Trigger:**\n");
        for (const action of step.uiActions) {
          sections.push(`- ${action}\n`);
        }
        sections.push("\n");
      }

      if (step.networkCalls.length > 0) {
        sections.push("**API Calls:**\n");
        for (const call of step.networkCalls) {
          sections.push(`- \`${call.method} ${call.url}\`\n`);
          sections.push(`  - Status: ${call.status}\n`);
        }
        sections.push("\n");
      }

      sections.push("---\n");
    }
  }

  return sections.join("");
}
