/**
 * OpenAPI documentation exporter
 */

import type { Flow } from "../agent/FlowTracker.js";
import { analyzeCapturedCalls, type CaptureAnalysis, type EndpointGroup, type SchemaNode } from "../analysis/index.js";
import type { CapturedCall } from "../browser/networkRecorder.js";

export interface OpenAPISpec {
  openapi: string;
  info: {
    title: string;
    version: string;
    description: string;
  };
  servers?: Array<{ url: string; description?: string }>;
  paths: Record<string, any>;
}

export function exportToOpenAPI(flows: Flow[]): OpenAPISpec {
  const paths: Record<string, any> = {};

  for (const flow of flows) {
    for (const step of flow.steps) {
      for (const call of step.networkCalls) {
        const urlObj = new URL(call.url);
        const path = urlObj.pathname;
        const method = call.method.toLowerCase();

        if (!paths[path]) paths[path] = {};
        if (!paths[path][method]) {
          paths[path][method] = {
            summary: `${method.toUpperCase()} ${path}`,
            description: `Triggered by: ${step.step}`,
            responses: {
              [call.status]: {
                description: `Status ${call.status}`,
              },
            },
          };
        }
      }
    }
  }

  return {
    openapi: "3.0.0",
    info: {
      title: "WebDoc Agent API Documentation",
      version: "1.0.0",
      description: "Generated by WebDoc Agent",
    },
    paths,
  };
}

export interface DocMetadata {
  capturedAt: string;
  sourceUrl: string;
  totalCalls: number;
  uniqueEndpoints: number;
  pagesExplored?: string[];
  sessionDuration?: string;
}

export function exportCallsToOpenAPI(
  calls: CapturedCall[],
  baseUrl: string,
  metadata?: DocMetadata,
): OpenAPISpec {
  const analysis = analyzeCapturedCalls(calls);
  const paths = buildPathsFromAnalysis(analysis);

  let hostname = "API";
  try {
    hostname = new URL(baseUrl).hostname;
  } catch {
    // ignore
  }

  const descriptionLines = [
    `Auto-generated by WebDoc Agent from observed browser traffic on ${hostname}.`,
    `Analyzed ${analysis.stats.apiCalls} API/polling call(s) across ${analysis.stats.uniqueEndpoints} endpoint group(s).`,
  ];

  if (metadata) {
    descriptionLines.push(`Captured: ${metadata.capturedAt}`);
    descriptionLines.push(
      `Source: ${metadata.sourceUrl} | ${metadata.totalCalls} total calls | ${metadata.uniqueEndpoints} unique endpoints`,
    );
    if (metadata.pagesExplored && metadata.pagesExplored.length > 0) {
      descriptionLines.push(`Pages explored: ${metadata.pagesExplored.join(", ")}`);
    }
    if (metadata.sessionDuration) {
      descriptionLines.push(`Session duration: ${metadata.sessionDuration}`);
    }
  }

  if (analysis.securitySignals.length > 0) {
    descriptionLines.push(
      `Security signals: ${analysis.securitySignals.map((signal) => `${signal.kind}:${signal.name}`).join(", ")}`,
    );
  }

  return {
    openapi: "3.0.0",
    info: {
      title: `${hostname} API Documentation`,
      version: "1.0.0",
      description: descriptionLines.join("\n"),
    },
    servers: [{ url: baseUrl }],
    paths,
  };
}

function buildPathsFromAnalysis(analysis: CaptureAnalysis): Record<string, any> {
  const paths: Record<string, any> = {};

  for (const endpoint of analysis.endpoints) {
    if (!paths[endpoint.displayPath]) {
      paths[endpoint.displayPath] = {};
    }

    paths[endpoint.displayPath][endpoint.method.toLowerCase()] = buildOperation(endpoint);
  }

  return paths;
}

function buildOperation(endpoint: EndpointGroup): any {
  const operation: any = {
    tags: [endpoint.resourceGroup],
    operationId: endpoint.operationName,
    summary: `${endpoint.method} ${endpoint.displayPath}`,
    description: buildEndpointDescription(endpoint),
    responses: Object.fromEntries(
      endpoint.statuses.map((status) => [
        status,
        {
          description: `Observed status ${status}`,
          ...(endpoint.responseSchema
            ? {
                content: {
                  "application/json": {
                    schema: schemaNodeToOpenAPI(endpoint.responseSchema),
                    ...(endpoint.responseExamples[0]
                      ? { example: endpoint.responseExamples[0] }
                      : {}),
                  },
                },
              }
            : {}),
        },
      ]),
    ),
  };

  if (endpoint.queryParams.length > 0 || endpoint.requestHeaders.length > 0) {
    operation.parameters = [
      ...endpoint.queryParams.map((param) => ({
        name: param.name,
        in: "query",
        required: false,
        schema: primitiveTypeToSchema(param.inferredType),
        description: `Observed ${param.observedCount} time(s)`,
        ...(param.values.length > 0 ? { example: param.values[0] } : {}),
      })),
      ...endpoint.requestHeaders.map((header) => ({
        name: header.name,
        in: "header",
        required: false,
        schema: { type: "string" },
        description: `${header.sensitive ? "Sensitive" : "Observed"} header`,
      })),
    ];
  }

  if (endpoint.requestSchema) {
    operation.requestBody = {
      content: {
        "application/json": {
          schema: schemaNodeToOpenAPI(endpoint.requestSchema),
          ...(endpoint.requestExamples[0] ? { example: endpoint.requestExamples[0] } : {}),
        },
      },
    };
  }

  return operation;
}

function buildEndpointDescription(endpoint: EndpointGroup): string {
  const lines = [
    `Observed ${endpoint.observedCalls} call(s).`,
    `Classified as ${endpoint.classifications.dataType}/${endpoint.classifications.interactionType}.`,
  ];

  if (endpoint.workflowBindings.length > 0) {
    lines.push(
      `Workflow context: ${endpoint.workflowBindings
        .map((binding) => binding.pageName || binding.triggerLabel || binding.flowName)
        .filter(Boolean)
        .join(", ")}`,
    );
  }

  if (endpoint.securitySignals.length > 0) {
    lines.push(
      `Security signals: ${endpoint.securitySignals.map((signal) => `${signal.kind}:${signal.name}`).join(", ")}`,
    );
  }

  return lines.join(" ");
}

function schemaNodeToOpenAPI(node: SchemaNode): any {
  switch (node.kind) {
    case "object":
      return {
        type: "object",
        properties: Object.fromEntries(
          Object.entries(node.properties || {}).map(([key, value]) => [key, schemaNodeToOpenAPI(value)]),
        ),
        ...(node.required && node.required.length > 0 ? { required: node.required } : {}),
        ...(node.nullable ? { nullable: true } : {}),
      };
    case "array":
      return {
        type: "array",
        items: node.items ? schemaNodeToOpenAPI(node.items) : {},
        ...(node.nullable ? { nullable: true } : {}),
      };
    case "integer":
      return { type: "integer", ...(node.nullable ? { nullable: true } : {}) };
    case "number":
      return { type: "number", ...(node.nullable ? { nullable: true } : {}) };
    case "boolean":
      return { type: "boolean", ...(node.nullable ? { nullable: true } : {}) };
    case "null":
      return { nullable: true };
    case "string": {
      const format = node.formats?.find((item) => item !== "unknown");
      const mappedFormat = format === "datetime" ? "date-time" : format === "iso-date" ? "date" : format;
      return {
        type: "string",
        ...(mappedFormat && mappedFormat !== "slug" && mappedFormat !== "jwt" ? { format: mappedFormat } : {}),
        ...(node.nullable ? { nullable: true } : {}),
      };
    }
    default:
      return { type: "string", ...(node.nullable ? { nullable: true } : {}) };
  }
}

function primitiveTypeToSchema(type: string): any {
  switch (type) {
    case "integer":
      return { type: "integer" };
    case "number":
      return { type: "number" };
    case "boolean":
      return { type: "boolean" };
    default:
      return { type: "string" };
  }
}
